# Generated by Django 4.1.1 on 2022-09-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('image', models.ImageField(upload_to='uploads/products/')),
                ('image2', models.ImageField(default='default.jpg', upload_to='uploads/products/')),
                ('image3', models.ImageField(default='default.jpg', upload_to='uploads/products/')),
            ],
        ),
    ]
